### ISSUE TITLE
Doesn't work with ruby 2.4

### ISSUE THREAD

**Issue by koooge** [ellekasai/resumecards#14]
When I exec `bundle isntall `, it occured an error.

```
$ bundle install

(snip)
Installing minima 2.0.0
Installing unicode-display_width 1.1.2
Using bundler 1.13.7
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/vagrant/resumecards/vendor/bundle/ruby/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/home/vagrant/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20170112-9119-nvrcar.rb extconf.rb
creating Makefile

current directory: /home/vagrant/resumecards/vendor/bundle/ruby/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /home/vagrant/resumecards/vendor/bundle/ruby/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function ‘generate_json’:
generator.c:861:25: error: ‘rb_cFixnum’ undeclared (first use in this function)
     } else if (klass == rb_cFixnum) {
                         ^
generator.c:861:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:863:25: error: ‘rb_cBignum’ undeclared (first use in this function)
     } else if (klass == rb_cBignum) {
                         ^
generator.c: At top level:
cc1: warning: unrecognized command line option "-Wno-self-assign"
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1: warning: unrecognized command line option "-Wno-tautological-compare"
Makefile:241: recipe for target 'generator.o' failed
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/vagrant/resumecards/vendor/bundle/ruby/2.4.0/gems/json-1.8.3 for inspection.
Results logged to /home/vagrant/resumecards/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```

Because Ruby 2.4 unifies Fixnum and Bignum into Integer.
If you'd like to fix this dependency. ♨️

**Comment by koooge** [comment]
This seems `github-pages ` gem's problem.
https://github.com/github/pages-gem/issues/376
